# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Compile TypeScript
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    # FIXME, COMMENTED OUT FOR TESTING
    # if: ${{ github.repository == 'microsoft/STL' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ">=17.5.0"
      - name: Install Packages
        run: |
          npm ci
      - name: Compile gather_stats.ts
        run: |
          npx tsc --noEmit
      - name: Compile status_chart.ts
        run: |
          npx tsc -p tsconfig.status_chart.json
